### ISSUE TITLE
'end' event never emitted with node v10.x

### ISSUE THREAD

**Issue by mickeyjohn** [MichaelQQ/dbfstream#7]
Hi,
Thanks for sharing the efficient dbf library. I found it works properly in node LTS 8.x (tested with 8.10 and 8.15.1) but can not get through 300 records in node 10 (10.15.0 and 10.15.3). The 'data' event stops getting called back at record 289 and the 'end' event never get fired. 

Any one know why? How about replacing "stream" with "readable-stream" (https://github.com/nodejs/readable-stream) for node 9 and 10 compatiblity ?

Thanks alot,
John

**Comment by MichaelQQ** [comment]
Hi @mickeyjohn,

I just published a new version 1.0.23 for fixing the issue on Node 10.
Thank you.

**Comment by mickeyjohn** [comment]
Hi MichaelQQ,
Thanks for the quick fix. However, I still find it stops at record 601 with with Node v10.15.1. Typically, It fires the 'header' event again then emit this error:

Error:  TypeError: Cannot read property 'length' of null
    at getListOfFields (.../node_modules/dbfstream/index.js:77:32)
    at Array.readHeader (.../node_modules/dbfstream/index.js:124:34)
    at ReadStream.readStream.on (.../node_modules/dbfstream/index.js:166:48)
    at ReadStream.emit (events.js:187:15)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
.../node_modules/dbfstream/index.js:166
      currentState = stateHandler[currentState]({
                                               ^

TypeError: stateHandler[currentState] is not a function
    at ReadStream.readStream.on (.../node_modules/dbfstream/index.js:166:48)
    at ReadStream.emit (events.js:187:15)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

In addition, It does not work with Node v8.15.x any longer so I have to switch back to version 1.0.21. Probably, this is caused by something relates to the breaking changes in stream of Node 8 and 10 in its dependencies?
Thank you.

**Comment by MichaelQQ** [comment]
Hi @mickeyjohn,

I just published 1.0.24. I've tested on Node 8 and 10, and it works fine on both version. 
Thank you.

**Comment by mickeyjohn** [comment]
Genius. Confirmed that v1.0.24 works with both Node 8 and 10. Great appreciated. Thank you.
